import { chromium } from 'playwright';
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => m.type() === 'error' && errs.push(m.text()));
await p.goto('http://localhost:4395/sitefront/nellies-private-dining-tholen/', { waitUntil: 'networkidle' });
await p.click('[data-kies="rijping"]'); await p.waitForTimeout(500);
await p.fill('input[name=aantal]', '6'); await p.selectOption('select[name=gelegenheid]', 'een verjaardag'); await p.fill('input[name=naam]', 'Test');
console.log(await p.textContent('[data-bericht-uit]')); console.log(decodeURIComponent(await p.getAttribute('[data-stuur]', 'href')));
await p.fill('input[name=datum]', '2026-12-18'); await p.dispatchEvent('input[name=datum]', 'change'); console.log('LET OP:', await p.textContent('[data-let-op]'));
await p.click('[data-datum="2026-10-23"]'); await p.waitForTimeout(300); console.log(await p.textContent('[data-bericht-uit]'), '|', await p.textContent('[data-let-op]'));
await p.fill('input[name=datum]', '2026-10-20'); await p.dispatchEvent('input[name=datum]', 'change'); console.log('LET OP:', await p.textContent('[data-let-op]'));
await p.click('[data-datum="2026-10-23"]'); await p.locator('#tafel').scrollIntoViewIfNeeded(); await p.waitForTimeout(1200); await p.screenshot({ path: 'shots/wow-1440.png' });
console.log('robots', await p.getAttribute('meta[name=robots]', 'content'), errs);
await b.close();
