import { chromium } from 'playwright';
const b = await chromium.launch(); const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } }); const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://localhost:4746/sitefront/oudshoorn-grondverzet-capelle/', { waitUntil: 'networkidle' });
await p.click('[data-filters] [data-cat="tuin"]');
console.log('zichtbaar tuin:', await p.$$eval('[data-projecten] > li', (l) => l.filter((x) => !x.hidden).length));
await p.click('[data-filters] [data-cat="alles"]');
await p.click('[data-project="7"]'); await p.waitForTimeout(800);
await p.keyboard.press('ArrowRight'); await p.waitForTimeout(800);
console.log(await p.textContent('[data-lb-titel]'), await p.textContent('[data-lb-teller]'));
await p.screenshot({ path: 'shots/lichtbak.png' });
await p.keyboard.press('Escape');
await p.click('label.keuze:has-text("Bestrating")'); await p.click('label.keuze:has-text("Riolering")');
await p.click('label.keuze:has-text("Bedrijf of instelling")');
await p.fill('input[name=plaats]', 'Capelle aan den IJssel'); await p.selectOption('select[name=wanneer]', 'Binnen een maand');
await p.fill('input[name=maat]', '120 m²'); await p.fill('input[name=naam]', 'Jan');
const [np] = await Promise.all([ctx.waitForEvent('page'), p.click('button[value=wa]')]);
console.log(decodeURIComponent(np.url()));
console.log(await p.textContent('[data-status]'), errs.join('|'));
await p.locator('.merk').first().screenshot({ path: 'shots/logo.png' });
await b.close();
