import { chromium } from 'playwright';
const b = await chromium.launch(); const ctx = await b.newContext(); const p = await ctx.newPage();
await p.goto('http://localhost:4707/sitefront/trimsalon-witte-rekeltjes-barendrecht/');
await p.fill('input[name=hond]', 'Baloo'); await p.fill('input[name=ras]', 'Golden Retriever');
await p.click('label.keuze:has-text("Volledige trimbeurt")'); await p.selectOption('select[name=dag]', 'Dinsdag');
await p.selectOption('select[name=deel]', 'In de ochtend'); await p.fill('input[name=naam]', 'Sanne'); await p.fill('textarea[name=wens]', 'graag kort');
const [np] = await Promise.all([ctx.waitForEvent('page'), p.click('button[type=submit]')]);
console.log(decodeURIComponent(np.url()));
console.log(await p.textContent('[data-status]'));
await b.close();
