import { chromium } from 'playwright';
const b = await chromium.launch(); const p = await (await b.newContext({ viewport: { width: 390, height: 844 } })).newPage();
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://127.0.0.1:4472/sitefront/wooncomfort-halsteren/', { waitUntil: 'networkidle' });
await p.click('[data-kies="een hordeur"]'); await p.waitForTimeout(900);
await p.selectOption('[data-plek]', 'de schuifpui of deur'); await p.fill('[data-breed]', '240');
console.log(await p.getAttribute('[data-stuur]', 'href'));
console.log(await p.textContent('[data-voorbeeld]'));
await p.locator('#offerte').screenshot({ path: 'shots/wow-390.png' });
console.log('errs', errs); await b.close();
